### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by ezidayzi** [29th-WE-SOPT-iOS-Part/KimYoonSeo#11]
## 📌  Feature Issue

데이터 연결 심화와 UIGestureRecognizer

## 📝  To-do

📝 To-do
- [x] imageView에 tap gesture
- [x] imageView가 tap 되었을 때, 화면전환
- [x] 화면전환시 데이터 전달
- [x] 전환된 뷰에서 버튼 누르면 dismiss
